# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import sys
from voltLinear import LinearVoltametry
from voltCyclic import CyclicVoltametry
from voltSquare import SquareWaveVoltametry
import pyqtgraph as pg
from PreDeposition import PreDeposition

# pg.setConfigOption('background', 'w')
pg.setConfigOption('background', 'w')
pg.setConfigOption('foreground', 'k')

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setWindowIcon(QtGui.QIcon('python_logo.png'))
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(417, 783)
        font = QtGui.QFont()
        font.setUnderline(True)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 0, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 710, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 351, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 417, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_file = QtGui.QMenu(self.menubar)
        self.menu_file.setObjectName(_fromUtf8("menu_file"))
        self.menu_Methood = QtGui.QMenu(self.menubar)
        self.menu_Methood.setObjectName(_fromUtf8("menu_Methood"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionSave_As.setStatusTip("Save the voltamogram")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionOpen.setStatusTip("Open a voltamogram")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionExit.setStatusTip("Close the App")
        self.actionExit.triggered.connect(self.close_app)
        self.actionLinear_Voltametry = QtGui.QAction(MainWindow)
        self.actionLinear_Voltametry.setObjectName(_fromUtf8("actionLinear_Voltametry"))
        self.actionLinear_Voltametry.triggered.connect(self.linear_voltametry)
        self.actionCyclic_Voltametry = QtGui.QAction(MainWindow)
        self.actionCyclic_Voltametry.setObjectName(_fromUtf8("actionCyclic_Voltametry"))
        self.actionCyclic_Voltametry.triggered.connect(self.cyclic_voltametry)
        self.actionSquare_Wave_Voltametry = QtGui.QAction(MainWindow)
        self.actionSquare_Wave_Voltametry.setObjectName(_fromUtf8("actionSquare_Wave_Voltametry"))
        self.actionSquare_Wave_Voltametry.triggered.connect(self.square_voltametry)
        self.actionCalibrate = QtGui.QAction(MainWindow)
        self.actionCalibrate.setObjectName(_fromUtf8("actionCalibrate"))
        self.actionConfigurations = QtGui.QAction(MainWindow)
        self.actionConfigurations.setObjectName(_fromUtf8("actionConfigurations"))
        self.menu_file.addAction(self.actionSave_As)
        self.menu_file.addAction(self.actionOpen)
        self.menu_file.addAction(self.actionExit)
        self.menu_Methood.addSeparator()
        self.menu_Methood.addAction(self.actionLinear_Voltametry)
        self.menu_Methood.addAction(self.actionCyclic_Voltametry)
        self.menu_Methood.addAction(self.actionSquare_Wave_Voltametry)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionCalibrate)
        self.menuSettings.addAction(self.actionConfigurations)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_Methood.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def linear_voltametry(self):
        MainWindow.close()
        Lin_window.show()

    def cyclic_voltametry(self):
        MainWindow.close()
        Cyc_window.show()

    def square_voltametry(self):
        MainWindow.close()
        Sqw_window.show()

    def close_app(self):
        choice = QtGui.QMessageBox.question(None,'Exit',
                                            'Are you sure?',
                                            QtGui.QMessageBox.Yes | QtGui.QMessageBox.No)
        if choice == QtGui.QMessageBox.Yes:
            sys.exit()
        else:
            pass


    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PotenciosPi", None))
        self.label.setText(_translate("MainWindow", "PotenciosPi:", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#005500;\">Universidade Estadual de Londrina</span></p><p align=\"center\"><span style=\" font-size:18pt;\"><br/></span></p></body></html>", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">A low cost open-source Raspberry Pi based potenciostat.</span></p></body></html>", None))
        self.label_4.setText(_translate("MainWindow", "Choose a method...", None))
        self.menu_file.setTitle(_translate("MainWindow", "&file", None))
        self.menu_Methood.setTitle(_translate("MainWindow", "&Methods", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuHelp.setTitle(_traLaTeX,nslate("MainWindow", "Help", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save As", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionLinear_Voltametry.setText(_translate("MainWindow", "Linear Voltametry", None))
        self.actionCyclic_Voltametry.setText(_translate("MainWindow", "Cyclic Voltametry", None))
        self.actionSquare_Wave_Voltametry.setText(_translate("MainWindow", "Square Wave Voltametry", None))
        self.actionCalibrate.setText(_translate("MainWindow", "Calibrate", None))
        self.actionConfigurations.setText(_translate("MainWindow", "Configurations", None))


class Ui_LinearWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowIcon(QtGui.QIcon('python_logo.png'))
        MainWindow.resize(804, 690)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.graphicsView = pg.PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(30, 340, 741, 291))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 290, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 0, 321, 41))
        self.label.setObjectName(_fromUtf8("label"))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(30, 800, 741, 16))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 151, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 141, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 270, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 170, 121, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 220, 121, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineVoltInitia = QtGui.QLineEdit(self.centralwidget)
        self.lineVoltInitia.setGeometry(QtCore.QRect(30, 90, 113, 21))
        self.lineVoltInitia.setObjectName(_fromUtf8("lineVoltInitia"))
        self.lineVoltInitia.setText("0")
        self.lineVoltFinal = QtGui.QLineEdit(self.centralwidget)
        self.lineVoltFinal.setGeometry(QtCore.QRect(30, 140, 113, 21))
        self.lineVoltFinal.setObjectName(_fromUtf8("lineVoltFinal"))
        self.lineVoltFinal.setText("600")
        self.lineVoltStep = QtGui.QLineEdit(self.centralwidget)
        self.lineVoltStep.setGeometry(QtCore.QRect(30, 190, 113, 21))
        self.lineVoltStep.setObjectName(_fromUtf8("lineVoltStep"))
        self.lineVoltStep.setText("10")
        self.lineVoltScan = QtGui.QLineEdit(self.centralwidget)
        self.lineVoltScan.setGeometry(QtCore.QRect(30, 240, 113, 21))
        self.lineVoltScan.setObjectName(_fromUtf8("lineVoltScan"))
        self.lineVoltScan.setText("50")
        self.lineVoltScans = QtGui.QLineEdit(self.centralwidget)
        self.lineVoltScans.setGeometry(QtCore.QRect(30, 290, 113, 21))
        self.lineVoltScans.setObjectName(_fromUtf8("lineVoltScans"))
        self.lineVoltScans.setText("1")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(160, 70, 20, 251))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(190, 90, 131, 21))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.linePreCond = QtGui.QLineEdit(self.centralwidget)
        self.linePreCond.setGeometry(QtCore.QRect(200, 140, 113, 21))
        self.linePreCond.setObjectName(_fromUtf8("linePreCond"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(190, 120, 151, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(190, 270, 121, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(190, 170, 141, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.linePreDep = QtGui.QLineEdit(self.centralwidget)
        self.linePreDep.setGeometry(QtCore.QRect(200, 240, 113, 21))
        self.linePreDep.setObjectName(_fromUtf8("linePreDep"))
        self.linePretime = QtGui.QLineEdit(self.centralwidget)
        self.linePretime.setGeometry(QtCore.QRect(200, 190, 113, 21))
        self.linePretime.setObjectName(_fromUtf8("linePretime"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(190, 220, 121, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.linePreDepTime = QtGui.QLineEdit(self.centralwidget)
        self.linePreDepTime.setGeometry(QtCore.QRect(200, 290, 113, 21))
        self.linePreDepTime.setObjectName(_fromUtf8("linePreDepTime"))
        self.spinBox = QtGui.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(370, 240, 42, 22))
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(360, 220, 61, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 40, 741, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 290, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_2.clicked.connect(self.run_linear)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(330, 70, 20, 251))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(360, 170, 101, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineDelayPoint = QtGui.QLineEdit(self.centralwidget)
        self.lineDelayPoint.setGeometry(QtCore.QRect(370, 190, 113, 21))
        self.lineDelayPoint.setObjectName(_fromUtf8("lineDelayPoint"))
        self.lineDelayPoint.setText("100")
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(360, 120, 141, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lineAcqPoint = QtGui.QLineEdit(self.centralwidget)
        self.lineAcqPoint.setGeometry(QtCore.QRect(370, 140, 113, 21))
        self.lineAcqPoint.setObjectName(_fromUtf8("lineAcqPoint"))
        self.lineAcqPoint.setText("300")
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(570, 140, 201, 181))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(570, 110, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Methods = QtGui.QMenu(self.menubar)
        self.menu_Methods.setObjectName(_fromUtf8("menu_Methods"))
        self.menu_Settings = QtGui.QMenu(self.menubar)
        self.menu_Settings.setObjectName(_fromUtf8("menu_Settings"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave.setStatusTip("Save the voltomogram")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionOpen.setStatusTip("Open a voltomogra,")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionExit.setStatusTip("Close the App")
        self.actionExit.triggered.connect(self.close_app)
        self.actionLinera = QtGui.QAction(MainWindow)
        self.actionLinera.setObjectName(_fromUtf8("actionLinera"))
        self.actionCyclic_Voltametry = QtGui.QAction(MainWindow)
        self.actionCyclic_Voltametry.setObjectName(_fromUtf8("actionCyclic_Voltametry"))
        self.actionCyclic_Voltametry.triggered.connect(self.cyclic_voltametry)
        self.actionSquare_Wave_Voltametry = QtGui.QAction(MainWindow)
        self.actionSquare_Wave_Voltametry.setObjectName(_fromUtf8("actionSquare_Wave_Voltametry"))
        self.actionSquare_Wave_Voltametry.triggered.connect(self.square_voltametry)
        self.actionCalibrate = QtGui.QAction(MainWindow)
        self.actionCalibrate.setObjectName(_fromUtf8("actionCalibrate"))
        self.actionConfigurations = QtGui.QAction(MainWindow)
        self.actionConfigurations.setObjectName(_fromUtf8("actionConfigurations"))
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addAction(self.actionExit)
        self.menu_Methods.addAction(self.actionLinera)
        self.menu_Methods.addAction(self.actionCyclic_Voltametry)
        self.menu_Methods.addAction(self.actionSquare_Wave_Voltametry)
        self.menu_Settings.addAction(self.actionCalibrate)
        self.menu_Settings.addAction(self.actionConfigurations)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Methods.menuAction())
        self.menubar.addAction(self.menu_Settings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def run_linear(self):
        if(self.checkBox.isChecked()):
            preCond = int(self.linePreCond.text())
            pre_time_cond = int(self.linePretime.text())
            pot_pre_dep = int(self.linePreDep.text())
            pre_deposition_time = int(self.linePreDepTime.text())

            i2 = PreDeposition(pot_cond = preCond, time_cond = pre_time_cond, pre_dep_pot=pot_pre_dep, pre_dep_time = pre_deposition_time, somadorDA = 3.0)
            i2.run()

        print(self.lineVoltInitia.text())
        potInii = int(self.lineVoltInitia.text())
        potFinn = int(self.lineVoltFinal.text())
        potStepp = int(self.lineVoltStep.text())
        potScann = int(self.lineVoltScan.text())
        potScanss = int(self.lineVoltScans.text())
        acq_pointss = int(self.lineAcqPoint.text())
        delay_pointss = int(self.lineDelayPoint.text())
        ganhoo = int(self.spinBox.text()) 

        i1 = LinearVoltametry(dac_sum=3.0,acq_points=acq_pointss,delay_points=delay_pointss,
                         potIni=potInii,potFin=potFinn,stepVolt=potStepp,ganho=ganhoo,scanRate=potScann)
        
        Ydata = []
        Xdata = []
    
        for x in i1.run():
            Xdata.append(x[0])
            Ydata.append(x[1])
        #    print(Xdata[0],Ydata[0])
        #    self.textBrowser.append(str([x[0],x[1]]))
            self.graphicsView.plot(Xdata, Ydata,clear=True)
            QtGui.QApplication.processEvents()
            #print([x[0],x[1]])     
            
    
    
    def cyclic_voltametry(self):
        Lin_window.close()
        Cyc_window.show()

    def square_voltametry(self):
        Lin_window.close()
        Sqw_window.show()

    def close_app(self):
        choice = QtGui.QMessageBox.question(None,'Exit',
                                            'Are you sure?',
                                            QtGui.QMessageBox.Yes | QtGui.QMessageBox.No)
        if choice == QtGui.QMessageBox.Yes:
            sys.exit()
        else:
            pass


    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Linear Voltametry", None))
        self.pushButton.setText(_translate("MainWindow", "Break", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">Linear Voltametry</span></p></body></html>", None))
        self.label_2.setText(_translate("MainWindow", "Initial potential (mV):", None))
        self.label_3.setText(_translate("MainWindow", "Final potential (mV):", None))
        self.label_4.setText(_translate("MainWindow", "Scans:", None))
        self.label_5.setText(_translate("MainWindow", "Step Voltage:", None))
        self.label_6.setText(_translate("MainWindow", "Scan Rate (mV/s):", None))
        self.checkBox.setText(_translate("MainWindow", "Pre deposition", None))
        self.label_7.setText(_translate("MainWindow", "Pre conditioning(mV):", None))
        self.label_8.setText(_translate("MainWindow", "Time (s)", None))
        self.label_9.setText(_translate("MainWindow", "Time (s):", None))
        self.label_10.setText(_translate("MainWindow", "Pre deposition(mV):", None))
        self.label_11.setText(_translate("MainWindow", "Ganho:", None))
        self.pushButton_2.setText(_translate("MainWindow", "Run", None))
        self.label_12.setText(_translate("MainWindow", "Delay Points:", None))
        self.label_13.setText(_translate("MainWindow", "Acquisition Points:", None))
        self.label_14.setText(_translate("MainWindow", "Status:", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Methods.setTitle(_translate("MainWindow", "&Methods", None))
        self.menu_Settings.setTitle(_translate("MainWindow", "&Settings", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionSave.setText(_translate("MainWindow", "Save As", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionLinera.setText(_translate("MainWindow", "Linear Voltametry", None))
        self.actionCyclic_Voltametry.setText(_translate("MainWindow", "Cyclic Voltametry", None))
        self.actionSquare_Wave_Voltametry.setText(_translate("MainWindow", "Square Wave Voltametry", None))
        self.actionCalibrate.setText(_translate("MainWindow", "Calibrate", None))
        self.actionConfigurations.setText(_translate("MainWindow", "Configurations", None))

class Ui_CyclicWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowIcon(QtGui.QIcon('python_logo.png'))
        MainWindow.resize(804, 690)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.graphicsView = pg.PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(30, 340, 741, 291))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 290, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 0, 321, 41))
        self.label.setObjectName(_fromUtf8("label"))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(30, 800, 741, 16))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 151, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 141, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 270, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 170, 121, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 220, 121, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineVoltInitia = QtGui.QLineEdit(self.centralwidget)
        self.lineVoltInitia.setGeometry(QtCore.QRect(30, 90, 113, 21))
        self.lineVoltInitia.setObjectName(_fromUtf8("lineVoltInitia"))
        self.lineVoltInitia.setText("0")
        self.lineVoltFinal = QtGui.QLineEdit(self.centralwidget)
        self.lineVoltFinal.setGeometry(QtCore.QRect(30, 140, 113, 21))
        self.lineVoltFinal.setObjectName(_fromUtf8("lineVoltFinal"))
        self.lineVoltFinal.setText("600")
        self.lineVoltStep = QtGui.QLineEdit(self.centralwidget)
        self.lineVoltStep.setGeometry(QtCore.QRect(30, 190, 113, 21))
        self.lineVoltStep.setObjectName(_fromUtf8("lineVoltStep"))
        self.lineVoltStep.setText("10")
        self.lineVoltScan = QtGui.QLineEdit(self.centralwidget)
        self.lineVoltScan.setGeometry(QtCore.QRect(30, 240, 113, 21))
        self.lineVoltScan.setObjectName(_fromUtf8("lineVoltScan"))
        self.lineVoltScan.setText("50")
        self.lineVoltScans = QtGui.QLineEdit(self.centralwidget)
        self.lineVoltScans.setGeometry(QtCore.QRect(30, 290, 113, 21))
        self.lineVoltScans.setObjectName(_fromUtf8("lineVoltScans"))
        self.lineVoltScans.setText("1")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(160, 70, 20, 251))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(190, 90, 131, 21))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.linePreCond = QtGui.QLineEdit(self.centralwidget)
        self.linePreCond.setGeometry(QtCore.QRect(200, 140, 113, 21))
        self.linePreCond.setObjectName(_fromUtf8("linePreCond"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(190, 120, 151, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(190, 270, 121, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(190, 170, 141, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.linePreDep = QtGui.QLineEdit(self.centralwidget)
        self.linePreDep.setGeometry(QtCore.QRect(200, 240, 113, 21))
        self.linePreDep.setObjectName(_fromUtf8("linePreDep"))
        self.linePretime = QtGui.QLineEdit(self.centralwidget)
        self.linePretime.setGeometry(QtCore.QRect(200, 190, 113, 21))
        self.linePretime.setObjectName(_fromUtf8("linePretime"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(190, 220, 121, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.linePreDepTime = QtGui.QLineEdit(self.centralwidget)
        self.linePreDepTime.setGeometry(QtCore.QRect(200, 290, 113, 21))
        self.linePreDepTime.setObjectName(_fromUtf8("linePreDepTime"))
        self.spinBox = QtGui.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(370, 240, 42, 22))
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(360, 220, 61, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 40, 741, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 290, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_2.clicked.connect(self.run_cyclic)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(330, 70, 20, 251))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(360, 170, 101, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineDelayPoint = QtGui.QLineEdit(self.centralwidget)
        self.lineDelayPoint.setGeometry(QtCore.QRect(370, 190, 113, 21))
        self.lineDelayPoint.setObjectName(_fromUtf8("lineDelayPoint"))
        self.lineDelayPoint.setText("100")
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(360, 120, 141, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lineAcqPoint = QtGui.QLineEdit(self.centralwidget)
        self.lineAcqPoint.setGeometry(QtCore.QRect(370, 140, 113, 21))
        self.lineAcqPoint.setObjectName(_fromUtf8("lineAcqPoint"))
        self.lineAcqPoint.setText("300")
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(570, 140, 201, 181))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(570, 110, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Methods = QtGui.QMenu(self.menubar)
        self.menu_Methods.setObjectName(_fromUtf8("menu_Methods"))
        self.menu_Settings = QtGui.QMenu(self.menubar)
        self.menu_Settings.setObjectName(_fromUtf8("menu_Settings"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave.setStatusTip("Save the voltomogram")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionOpen.setStatusTip("Open a voltomogram")
        selfgraphicsView.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionExit.setStatusTip("Close the App")
        self.actionExit.triggered.connect(self.close_app)
        self.actionLinera = QtGui.QAction(MainWindow)
        self.actionLinera.setObjectName(_fromUtf8("actionLinera"))
        self.actionLinera.triggered.connect(self.linear_voltametry)
        self.actionCyclic_Voltametry = QtGui.QAction(MainWindow)
        self.actionCyclic_Voltametry.setObjectName(_fromUtf8("actionCyclic_Voltametry"))
        self.actionSquare_Wave_Voltametry = QtGui.QAction(MainWindow)
        self.actionSquare_Wave_Voltametry.setObjectName(_fromUtf8("actionSquare_Wave_Voltametry"))
        self.actionSquare_Wave_Voltametry.triggered.connect(self.square_voltametry)
        self.actionCalibrate = QtGui.QAction(MainWindow)
        self.actionCalibrate.setObjectName(_fromUtf8("actionCalibrate"))
        self.actionConfigurations = QtGui.QAction(MainWindow)
        self.actionConfigurations.setObjectName(_fromUtf8("actionConfigurations"))
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addAction(self.actionExit)
        self.menu_Methods.addAction(self.actionLinera)
        self.menu_Methods.addAction(self.actionCyclic_Voltametry)
        self.menu_Methods.addAction(self.actionSquare_Wave_Voltametry)
        self.menu_Settings.addAction(self.actionCalibrate)
        self.menu_Settings.addAction(self.actionConfigurations)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Methods.menuAction())
        self.menubar.addAction(self.menu_Settings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def run_cyclic(self):
        if(self.checkBox.isChecked()):
            preCond = int(self.linePreCond.text())
            pre_time_cond = int(self.linePretime.text())
            pot_pre_dep = int(self.linePreDep.text())
            pre_deposition_time = int(self.linePreDepTime.text())

            i2 = PreDeposition(pot_cond = preCond, time_cond = pre_time_cond, pre_dep_pot=pot_pre_dep, pre_dep_time = pre_deposition_time, somadorDA = 3.0)
            i2.run()

        print(self.lineVoltInitia.text())
        potInii = int(self.lineVoltInitia.text())
        potFinn = int(self.lineVoltFinal.text())
        potStepp = int(self.lineVoltStep.text())
        potScann = int(self.lineVoltScan.text())
        potScanss = int(self.lineVoltScans.text())
        acq_pointss = int(self.lineAcqPoint.text())
        delay_pointss = int(self.lineDelayPoint.text())
        ganhoo = int(self.spinBox.text()) 


        i1 = CyclicVoltametry(dac_sum=3.0,acq_points=acq_pointss,delay_points=delay_pointss,
                         potIni=potInii,potFin=potFinn,stepVolt=potStepp,ganho=ganhoo,scanRate=potScann)

        Ydata = []
        Xdata = []
        for x in i1.run():
            Xdata.append(x[0])
            Ydata.append(x[1])
            # print(data[0],data[1])
            self.textBrowser.append(str([x[0], x[1]]))
            self.graphicsView.plot(Xdata, Ydata, clear=True)
            QtGui.QApplication.processEvents()
            print([x[0], x[1]])

    def linear_voltametry(self):
        Cyc_window.close()
        Lin_window.show()

    def square_voltametry(self):
        Cyc_window.close()
        Sqw_window.show()

    def close_app(self):
        choice = QtGui.QMessageBox.question(None,'Exit',
                                            'Are you sure?',
                                            QtGui.QMessageBox.Yes | QtGui.QMessageBox.No)
        if choice == QtGui.QMessageBox.Yes:
            sys.exit()
        else:
            pass



    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Cyclic Voltametry", None))
        self.pushButton.setText(_translate("MainWindow", "Break", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">Cyclic Voltametry</span></p></body></html>", None))
        self.label_2.setText(_translate("MainWindow", "Initial potential (mV):", None))
        self.label_3.setText(_translate("MainWindow", "Final potential (mV):", None))
        self.label_4.setText(_translate("MainWindow", "Scans:", None))
        self.label_5.setText(_translate("MainWindow", "Step Voltage:", None))
        self.label_6.setText(_translate("MainWindow", "Scan Rate (mV/s):", None))
        self.checkBox.setText(_translate("MainWindow", "Pre deposition", None))
        self.label_7.setText(_translate("MainWindow", "Pre conditioning (mV):", None))
        self.label_8.setText(_translate("MainWindow", "Time (s)", None))
        self.label_9.setText(_translate("MainWindow", "Time (s):", None))
        self.label_10.setText(_translate("MainWindow", "Pre deposition(mV)", None))
        self.label_11.setText(_translate("MainWindow", "Ganho:", None))
        self.pushButton_2.setText(_translate("MainWindow", "Run", None))
        self.label_12.setText(_translate("MainWindow", "Delay Points:", None))
        self.label_13.setText(_translate("MainWindow", "Acquisition Points:", None))
        self.label_14.setText(_translate("MainWindow", "Status:", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Methods.setTitle(_translate("MainWindow", "&Methods", None))
        self.menu_Settings.setTitle(_translate("MainWindow", "&Settings", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionSave.setText(_translate("MainWindow", "Save As", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionLinera.setText(_translate("MainWindow", "Linear Voltametry", None))
        self.actionCyclic_Voltametry.setText(_translate("MainWindow", "Cyclic Voltametry", None))
        self.actionSquare_Wave_Voltametry.setText(_translate("MainWindow", "Square Wave Voltametry", None))
        self.actionCalibrate.setText(_translate("MainWindow", "Calibrate", None))
        self.actionConfigurations.setText(_translate("MainWindow", "Configurations", None))



class Ui_SquareWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowIcon(QtGui.QIcon('python_logo.png'))
        MainWindow.resize(804, 690)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.graphicsView = pg.PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(30, 340, 741, 291))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 290, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 0, 321, 41))
        self.label.setObjectName(_fromUtf8("label"))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(30, 800, 741, 16))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 151, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 141, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 270, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 170, 121, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 220, 121, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineVoltInitia = QtGui.QLineEdit(self.centralwidget)
        self.lineVoltInitia.setGeometry(QtCore.QRect(30, 90, 113, 21))
        self.lineVoltInitia.setObjectName(_fromUtf8("lineVoltInitia"))
        self.lineVoltInitia.setText("0")
        self.lineVoltFinal = QtGui.QLineEdit(self.centralwidget)
        self.lineVoltFinal.setGeometry(QtCore.QRect(30, 140, 113, 21))
        self.lineVoltFinal.setObjectName(_fromUtf8("lineVoltFinal"))
        self.lineVoltFinal.setText("600")
        self.lineVoltStep = QtGui.QLineEdit(self.centralwidget)
        self.lineVoltStep.setGeometry(QtCore.QRect(30, 190, 113, 21))
        self.lineVoltStep.setObjectName(_fromUtf8("lineVoltStep"))
        self.lineVoltStep.setText("10")
        self.lineVoltScan = QtGui.QLineEdit(self.centralwidget)
        self.lineVoltScan.setGeometry(QtCore.QRect(30, 240, 113, 21))
        self.lineVoltScan.setObjectName(_fromUtf8("lineVoltScan"))
        self.lineVoltScan.setText("50")
        self.lineVoltScans = QtGui.QLineEdit(self.centralwidget)
        self.lineVoltScans.setGeometry(QtCore.QRect(30, 290, 113, 21))
        self.lineVoltScans.setObjectName(_fromUtf8("lineVoltScans"))
        self.lineVoltScans.setText("1")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(160, 70, 20, 251))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(190, 90, 131, 21))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.linePreCond = QtGui.QLineEdit(self.centralwidget)
        self.linePreCond.setGeometry(QtCore.QRect(200, 140, 113, 21))
        self.linePreCond.setObjectName(_fromUtf8("linePreCond"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(190, 120, 151, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(190, 270, 121, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(190, 170, 141, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.linePreDep = QtGui.QLineEdit(self.centralwidget)
        self.linePreDep.setGeometry(QtCore.QRect(200, 240, 113, 21))
        self.linePreDep.setObjectName(_fromUtf8("linePreDep"))
        self.linePretime = QtGui.QLineEdit(self.centralwidget)
        self.linePretime.setGeometry(QtCore.QRect(200, 190, 113, 21))
        self.linePretime.setObjectName(_fromUtf8("linePretime"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(190, 220, 121, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.linePreDepTime = QtGui.QLineEdit(self.centralwidget)
        self.linePreDepTime.setGeometry(QtCore.QRect(200, 290, 113, 21))
        self.linePreDepTime.setObjectName(_fromUtf8("linePreDepTime"))
        self.spinBox = QtGui.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(370, 240, 42, 22))
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(360, 220, 61, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 40, 741, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 290, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_2.clicked.connect(self.run_SQW)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(330, 70, 20, 251))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(360, 170, 101, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineDelayPoint = QtGui.QLineEdit(self.centralwidget)
        self.lineDelayPoint.setGeometry(QtCore.QRect(370, 190, 113, 21))
        self.lineDelayPoint.setObjectName(_fromUtf8("lineDelayPoint"))
        self.lineDelayPoint.setText("100")
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(360, 120, 141, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lineAcqPoint = QtGui.QLineEdit(self.centralwidget)
        self.lineAcqPoint.setGeometry(QtCore.QRect(370, 140, 113, 21))
        self.lineAcqPoint.setObjectName(_fromUtf8("lineAcqPoint"))
        self.lineAcqPoint.setText("300")
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(570, 140, 201, 181))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(570, 110, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Methods = QtGui.QMenu(self.menubar)
        self.menu_Methods.setObjectName(_fromUtf8("menu_Methods"))
        self.menu_Settings = QtGui.QMenu(self.menubar)
        self.menu_Settings.setObjectName(_fromUtf8("menu_Settings"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave.setStatusTip("Salva o voltomograma")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionOpen.setStatusTip("Abre voltomograma")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionExit.setStatusTip("Fecha o App")
        self.actionExit.triggered.connect(self.close_app)
        self.actionLinera = QtGui.QAction(MainWindow)
        self.actionLinera.setObjectName(_fromUtf8("actionLinera"))
        self.actionLinera.triggered.connect(self.linear_voltametry)
        self.actionCyclic_Voltametry = QtGui.QAction(MainWindow)
        self.actionCyclic_Voltametry.setObjectName(_fromUtf8("actionCyclic_Voltametry"))
        self.actionCyclic_Voltametry.triggered.connect(self.cyclic_voltametry)
        self.actionSquare_Wave_Voltametry = QtGui.QAction(MainWindow)
        self.actionSquare_Wave_Voltametry.setObjectName(_fromUtf8("actionSquare_Wave_Voltametry"))
        self.actionCalibrate = QtGui.QAction(MainWindow)
        self.actionCalibrate.setObjectName(_fromUtf8("actionCalibrate"))
        self.actionConfigurations = QtGui.QAction(MainWindow)
        self.actionConfigurations.setObjectName(_fromUtf8("actionConfigurations"))
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addAction(self.actionExit)
        self.menu_Methods.addAction(self.actionLinera)
        self.menu_Methods.addAction(self.actionCyclic_Voltametry)
        self.menu_Methods.addAction(self.actionSquare_Wave_Voltametry)
        self.menu_Settings.addAction(self.actionCalibrate)
        self.menu_Settings.addAction(self.actionConfigurations)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Methods.menuAction())
        self.menubar.addAction(self.menu_Settings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def run_SQW(self):
        if(self.checkBox.isChecked()):
            preCond = int(self.linePreCond.text())
            pre_time_cond = int(self.linePretime.text())
            pot_pre_dep = int(self.linePreDep.text())
            pre_deposition_time = int(self.linePreDepTime.text())

            i2 = PreDeposition(pot_cond = preCond, time_cond = pre_time_cond, pre_dep_pot=pot_pre_dep, pre_dep_time = pre_deposition_time, somadorDA = 3.0)
            i2.run()
        print(self.lineVoltInitia.text())
        potInii = int(self.lineVoltInitia.text())
        potFinn = int(self.lineVoltFinal.text())
        potStepp = int(self.lineVoltStep.text())
        potScann = int(self.lineVoltScan.text())
        potScanss = int(self.lineVoltScans.text())
        acq_pointss = int(self.lineAcqPoint.text())
        delay_pointss = int(self.lineDelayPoint.text())
        ganhoo = int(self.spinBox.text()) 
        
        i1 = SquareWaveVoltametry(dac_sum=3.0,acq_points=acq_pointss,delay_points=delay_pointss,
                         potIni=potInii,potFin=potFinn,stepVolt=potStepp,ganho=ganhoo,ampP=50,freq=10)

        Ydata = []
        Xdata = []
        for x in i1.run():
            Xdata.append(x[0])
            Ydata.append(x[1])
            # print(data[0],data[1])
            self.textBrowser.append(str([x[0], x[1]]))
            self.graphicsView.plot(Xdata, Ydata, clear=True)
            QtGui.QApplication.processEvents()
            print([x[0], x[1]])

    def linear_voltametry(self):
        Sqw_window.close()
        Lin_window.show()

    def cyclic_voltametry(self):
        Sqw_window.close()
        Cyc_window.show()

    def close_app(self):
        choice = QtGui.QMessageBox.question(None,'Exit',
                                            'Are you sure?',
                                            QtGui.QMessageBox.Yes | QtGui.QMessageBox.No)
        if choice == QtGui.QMessageBox.Yes:
            sys.exit()
        else:
            pass


    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Square Wave Voltametry", None))
        self.pushButton.setText(_translate("MainWindow", "Break", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">Square Wave</span></p></body></html>", None))
        self.label_2.setText(_translate("MainWindow", "Initial potential (mV):", None))
        self.label_3.setText(_translate("MainWindow", "Final potential (mV):", None))
        self.label_4.setText(_translate("MainWindow", "Scans:", None))
        self.label_5.setText(_translate("MainWindow", "Step Voltage:", None))
        self.label_6.setText(_translate("MainWindow", "Scan Rate (mV/s):", None))
        self.checkBox.setText(_translate("MainWindow", "Pre deposition", None))
        self.label_7.setText(_translate("MainWindow", "Pre conditioning (mV):", None))
        self.label_8.setText(_translate("MainWindow", "Time (s)", None))
        self.label_9.setText(_translate("MainWindow", "Time (s):", None))
        self.label_10.setText(_translate("MainWindow", "Pre deposition(mV)", None))
        self.label_11.setText(_translate("MainWindow", "Ganho:", None))
        self.pushButton_2.setText(_translate("MainWindow", "Run", None))
        self.label_12.setText(_translate("MainWindow", "Delay Points:", None))
        self.label_13.setText(_translate("MainWindow", "Acquisition Points:", None))
        self.label_14.setText(_translate("MainWindow", "Status:", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Methods.setTitle(_translate("MainWindow", "&Methods", None))
        self.menu_Settings.setTitle(_translate("MainWindow", "&Settings", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionSave.setText(_translate("MainWindow", "Save As", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionLinera.setText(_translate("MainWindow", "Linear Voltametry", None))
        self.actionCyclic_Voltametry.setText(_translate("MainWindow", "Cyclic Voltametry", None))
        self.actionSquare_Wave_Voltametry.setText(_translate("MainWindow", "Square Wave Voltametry", None))
        self.actionCalibrate.setText(_translate("MainWindow", "Calibrate", None))
        self.actionConfigurations.setText(_translate("MainWindow", "Configurations", None))


if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    Lin_window = QtGui.QMainWindow()
    Lin = Ui_LinearWindow()
    Lin.setupUi(Lin_window)

    Cyc_window = QtGui.QMainWindow()
    Cyc = Ui_CyclicWindow()
    Cyc.setupUi(Cyc_window)

    Sqw_window = QtGui.QMainWindow()
    Sqw = Ui_SquareWindow()
    Sqw.setupUi(Sqw_window)


    sys.exit(app.exec_())
